---
- name: Playbook for sec groups
  hosts: localhost
  tasks:
    - name: Create Sec Group1
      ec2_group:
        name: "{{ sg_name }}"
        description: ansible security group
        vpc_id: "{{vpc_id}}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            - 80
            - 443
            - 1167
            cidr_ip: 0.0.0.0/0