---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: VPC for class
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tags:
          Class: Ansible
          Task: VPC

    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: us-east-1
        az: us-east-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.0.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet

     - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: us-east-1
        az: us-east-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.0.2.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet

     - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: us-east-1
        az: us-east-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.0.3.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet 
      
    - name: Create subnet for  web servers
      ec2_vpc_subnet:
        state: present
        region: us-east-1
        az: us-east-1b
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.0.11.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet

    - name: Create subnet for web servers
       ec2_vpc_subnet:
         state: present
         region: us-east-1
         az: us-east-1b
         vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
         cidr: 10.0.12.0/24
         resource_tags:
          Name: Public Subnet
      register: public_subnet  
    
    - name: Create subnet for web servers
      ec2_vpc_subnet:
        state: present
        region: us-east-1
        az: us-east-1b
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.0.13.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet  
      