---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Loop
      package:
        name:
        state: present
      with_items:
        - httpd
        - telnet
        - lftp
        - wget
        - unzip 

    - name: Command
      command: "{{item}}"
      with_items:
        - "yum install telnet -y"
        - "free -m"
        - "w"